### ISSUE TITLE
Question: possible to adjust Parameters from command line?

### ISSUE THREAD

**Issue by alexandertuna** [key4hep/k4MarlinWrapper#192]
Hi developers,

When running `k4run`, is it possible to change a specific Parameter of a MarlinProcessorWrapper instance from the command line? I tried a few things, and I'm not sure if it's possible, and I want to check with you.

For example, in `k4MarlinWrapper/examples/event_display.py`:

```
MyCEDViewer = MarlinProcessorWrapper("MyCEDViewer")
MyCEDViewer.OutputLevel = INFO
MyCEDViewer.ProcessorType = "DDCEDViewer"
MyCEDViewer.Parameters = {
                          "ColorByEnergy": ["false"],
                          "ColorByEnergyAutoColor": ["false"],
                          "ColorByEnergyBrightness": ["1.0"],
                          "ColorByEnergyMax": ["35.0"],
                          "ColorByEnergyMin": ["0.0"],
```

In this example, is it possible to set `MyCEDViewer.Parameters.ColorByEnergyMax = 50` from the command line without changing the other Parameters in the config file?

Thanks for your help!
Alex

**Comment by tmadlener** [comment]
Hi Alex, 

in principle it would be possible, via `--<algo-name>.<param-name>`. However, for all the `MarlinProcessorWrapper` instances this is not really useful, because all of it's parameters live inside one `Parameters` steering parameter. It's better for "true" Gaudi algorithms.

If you only have one or a few parameters that you want to control from the command line you can use [this](https://key4hep.github.io/key4hep-doc/how-tos/k4fwcore/doc/k4run-args.html) to add your own arguments to the machinery. (`event_display` has a few already).

Cheers,
Thomas

**Comment by alexandertuna** [comment]
Thanks @tmadlener. I think adding a few arguments is a reasonable suggestion which could work for us. I'll try it.
